### ISSUE TITLE
A node disappeared from listed nodes, unacked heartbeats probably led to that

### ISSUE THREAD

**Issue by bogdando** [cloudnull/directord#260]
**Describe the bug**
A job ID 41fcba15-6d53-4de7-9452-475b3a8ccabb failed since node1 suddenly disappeared from directord nodes listed . https://paste.opendev.org/show/b972ZzwGQbSJqQ0KIfHW/ shows events flow.

**To Reproduce**
follow https://etherpad.opendev.org/p/tripleo-directord-hackfest

**Expected behavior**
node1 should not disappear. It kept sending heartbeats, but those weren't confirmed by server

**Operating System:**
 - OS: Centos
 - Version 8 Stream

**Python Version:**
 - Version Python 3.8.12

**Additional context**
Python 3.8.12 (default, Sep 21 2021, 00:10:52) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux

The problem was hit while running OpenStack 2021 PTG directord hackfest

**Comment by bogdando** [comment]
It may be, could we focus on the reported situation yet, not on the root cause of the interrupted heartbeats flow, but better debugging/recovery for such situations? E.g. would be nice to track IDs to match send/recieved hearteats

**Comment by cloudnull** [comment]
> Thank you @cloudnull . Perhaps keeping (seemingly) dead nodes in the list makes sense, if you think of large environments with hundreds of nodes. There should be a way to quickly re-add node back, or check its state - is it still dead, and/or to decide either to remove it or fence/unfence.

So I was thinking about this. Directord will never address or send work to a dead client; infact it'll raise if a client is specifically defined by a user but not found within it's running inventory. So, maybe we could move dead clients to a dead client list and show that information when running `--node-list`? It'd just be an esthetic change from the user POV. If the node starts checking in again the reference would be updated.
